name: Java CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests and Generate Report
        run: mvn test surefire-report:report

      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: target/site/surefire-report.html